### PR TITLE
Updated the Readme file, created contributing.md

### PR DESCRIPTION
**Pull request by Oghenebrume50**
Did some update to the readme file and created a contributing file for further details on how to contribute to this project. check it out @amaechi-chuks

### CODE REVIEW

**Review by amaechi-chuks — APPROVED** [review]
The update is cool, but we would like something more technical.

**Comment by amaechi-chuks** [comment]
Thanks for the progress.

**Comment by Oghenebrume50** [comment]
Yeah still looking at the files, We need to deliberate on the definite part to progress we want, But I'll  try to setup  the back end by this week's end

**Comment by Oghenebrume50** [comment]
Yeah still looking at the files, We need to deliberate on the definite part to progress we want, But I'll  try to setup  the back end by this week's end

**Pull request merged**
